site_name: chAI
theme: 
  name: material
  palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-2
          name: Switch to light mode
  features:
      - navigation.left
      - navigation.expand
      - navigation.top
      - search.suggest
      - search.highlight
      - toc.follow
repo_name: chAI
repo_url: https://github.com/co-cddo/gds-ideas-chai

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
        permalink: true

plugins:
  - glightbox
  - search 
  - mkdocstrings:
        default_handler: python
        handlers:
          python:
            paths: [.]
            options:
              show_root_heading: true
              show_category_heading: true
              show_submodules: true

nav:
  - Home: README.md
  - API Reference:
    - chAI: reference/chai.md
    - Requests: reference/requests.md
    - Config: reference/config.md

watch:
  - src/chai