name: Publish Package
# This workflow is manually triggered
on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Deploy target'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  deploy-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for pushing tags/commits
      id-token: write # Need this for PyPi verification
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for version calculation
      
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      
      - name: Install the project
        run: uv sync --all-extras --dev
      
      - name: Run tests
        run: uv run pytest
      
      - name: Get current version
        id: get_version
        run: |
          # Get current version from pyproject.toml
          CURRENT_VERSION=$(grep -m 1 'version = ' pyproject.toml | sed -E 's/.*version = "([^"]+)".*/\1/')
          echo "Current version: $CURRENT_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          
          # Create a tag if deploying to PyPI
          if [ "${{ github.event.inputs.deploy_target }}" == "pypi" ]; then
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              git tag -a "v${CURRENT_VERSION}" -m "Version ${CURRENT_VERSION}"
              git push --tags
          fi
      
      - name: Clean previous builds
        run: |
          # Completely delete and recreate dist and build directories
          rm -rf dist/
          rm -rf build/
          rm -rf *.egg-info/
          mkdir -p dist
          mkdir -p build
          
          # Verify they're empty
          echo "Checking dist directory:"
          ls -la dist/ || echo "dist/ is empty"
          echo "Checking build directory:"
          ls -la build/ || echo "build/ is empty"
      
      - name: Build package
        run: |
          # Build the package
          uv build
          
          # List the generated files to verify correct versioning
          echo "Files in dist directory:"
          ls -la dist/
      
      - name: Publish to TestPyPI
        if: github.event.inputs.deploy_target == 'testpypi'
        run: uv publish --token "${{ secrets.TEST_PYPI_CHAI_LLM }}" --publish-url https://test.pypi.org/legacy/
      
      - name: Publish to PyPI
        if: github.event.inputs.deploy_target == 'pypi'
        run: uv publish --token "${{ secrets.PYPI_CHAI_LLM }}"